/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1A1A1E",
        "tertiary-fixed-dim": "#FBE4E7",
        "on-tertiary-fixed": "#1A1A1E",
        "background": "#fff0f2",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#f7a0b2",
        "tertiary": "#4A4A52",
        "outline": "#4A4A52",
        "on-secondary-fixed-variant": "#4A4A52",
        "on-tertiary-fixed-variant": "#4A4A52",
        "surface-bright": "#FFFFFF",
        "on-primary-fixed": "#FFFFFF",
        "surface-container-low": "#fff0f2",
        "surface-container": "#fff0f2",
        "surface-variant": "#FBE4E7",
        "tertiary-fixed": "#FBE4E7",
        "error-container": "#FBE4E7",
        "secondary-container": "#fde8ed",
        "on-surface-variant": "#4A4A52",
        "outline-variant": "#C9C9CF",
        "on-surface": "#1A1A1E",
        "surface-container-lowest": "#FFFFFF",
        "inverse-surface": "#6A040F",
        "on-tertiary": "#ffffff",
        "on-background": "#1A1A1E",
        "inverse-on-surface": "#fff0f2",
        "on-primary-container": "#ffffff",
        "surface-container-high": "#fff0f2",
        "on-secondary": "#ffffff",
        "secondary": "#f47a90",
        "surface-dim": "#FBE4E7",
        "error": "#f04163",
        "on-error": "#ffffff",
        "tertiary-container": "#6A040F",
        "on-secondary-container": "#1A1A1E",
        "surface": "#FFFFFF",
        "primary-fixed-dim": "#FBE4E7",
        "primary-container": "#f04163",
        "surface-container-highest": "#FBE4E7",
        "primary": "#f04163",
        "on-tertiary-container": "#fff0f2",
        "primary-fixed": "#FBE4E7",
        "secondary-fixed": "#fbc4ce",
        "inverse-primary": "#E63946",
        "on-error-container": "#c5304f",
        "surface-tint": "#f04163",
        "on-primary-fixed-variant": "#c5304f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        lg: "24px",
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "pulse-ring": {
          "0%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(240, 65, 99, 0.7)" },
          "70%": { transform: "scale(1)", boxShadow: "0 0 0 10px rgba(240, 65, 99, 0)" },
          "100%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(240, 65, 99, 0)" },
        },
      },
      animation: {
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite",
      },
    },
  },
  plugins: [],
};

