/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1d1b1b",
        "tertiary-fixed-dim": "#dfbfbe",
        "on-tertiary-fixed": "#291717",
        "background": "#fff8f7",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#cbc5c5",
        "tertiary": "#5f4747",
        "outline": "#8f6f6f",
        "on-secondary-fixed-variant": "#494646",
        "on-tertiary-fixed-variant": "#584141",
        "surface-bright": "#fff8f7",
        "on-primary-fixed": "#40000a",
        "surface-container-low": "#fff0f0",
        "surface-container": "#ffe9e8",
        "surface-variant": "#f9dcdb",
        "tertiary-fixed": "#fcdbd9",
        "error-container": "#ffdad6",
        "secondary-container": "#e5dede",
        "on-surface-variant": "#5b4040",
        "outline-variant": "#e3bebd",
        "on-surface": "#271718",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#3e2c2c",
        "on-tertiary": "#ffffff",
        "on-background": "#271718",
        "inverse-on-surface": "#ffedec",
        "on-primary-container": "#ffdada",
        "surface-container-high": "#ffe1e1",
        "on-secondary": "#ffffff",
        "secondary": "#615d5e",
        "surface-dim": "#f0d3d3",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-container": "#785f5e",
        "on-secondary-container": "#666262",
        "surface": "#fff8f7",
        "primary-fixed-dim": "#ffb3b4",
        "primary-container": "#c41e3a",
        "surface-container-highest": "#f9dcdb",
        "primary": "#9e0027",
        "on-tertiary-container": "#fddbda",
        "primary-fixed": "#ffdad9",
        "secondary-fixed": "#e7e1e1",
        "inverse-primary": "#ffb3b4",
        "on-error-container": "#93000a",
        "surface-tint": "#ba1434",
        "on-primary-fixed-variant": "#920023",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        lg: "24px",
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "pulse-ring": {
          "0%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(186, 26, 26, 0.7)" },
          "70%": { transform: "scale(1)", boxShadow: "0 0 0 10px rgba(186, 26, 26, 0)" },
          "100%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(186, 26, 26, 0)" },
        },
      },
      animation: {
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite",
      },
    },
  },
  plugins: [],
};

